- id: commitizen
  name: commitizen check
  description: "Check whether the commit message follows commiting rules"
  entry: cz check
  args: [--allow-abort, --commit-msg-file]
  stages: [commit-msg]
  language: python
  language_version: python3
  minimum_pre_commit_version: "1.4.3"
