from __future__ import annotations

import pytest

from commitizen.bump_rule import VersionIncrement
from commitizen.version_schemes import Prerelease, SemVer, VersionProtocol
from tests.utils import VersionSchemeTestArgs


@pytest.mark.parametrize(
    "version_args, expected_version",
    [
        (
            VersionSchemeTestArgs(
                current_version="0.1.1",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.1.2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.1.1",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.2.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="2.1.1",
                increment=VersionIncrement.MAJOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "3.0.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.9.0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.9.1-a0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.9.0",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.10.0-a0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.9.0",
                increment=VersionIncrement.MAJOR,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.9.0",
                increment=VersionIncrement.MAJOR,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=1,
                devrelease=None,
            ),
            "1.0.0-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a2",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-b0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a2",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=1,
                devrelease=None,
            ),
            "1.0.0-b1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0beta1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-rc0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-rc2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0-a0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-rc0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0-alpha1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a2",
        ),
        # weird cases
        (
            VersionSchemeTestArgs(
                current_version="1.1",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1",
                increment=VersionIncrement.MAJOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "2.0.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1a0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1a0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=1,
                devrelease=None,
            ),
            "1.0.0-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-b0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=1,
                devrelease=None,
            ),
            "1.0.0-b1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1beta",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-b1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0alpha1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-rc0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc1+e20d7b57f3eb",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0",
        ),
        # simple flow
        (
            VersionSchemeTestArgs(
                current_version="0.1.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.1.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.1.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=1,
            ),
            "0.1.1-dev1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.1.1",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.2.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.2.0",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.3.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.2.0",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=1,
            ),
            "0.3.0-dev1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.3.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.3.1-a0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.1a0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.3.1-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=1,
                devrelease=None,
            ),
            "0.3.1-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.1a0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=1,
                devrelease=None,
            ),
            "0.3.1-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.1a0",
                increment=VersionIncrement.NONE,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.3.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.3.1",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.3.2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.4.2",
                increment=VersionIncrement.MAJOR,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-a2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=1,
            ),
            "1.0.0-a2-dev1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a2.dev0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=1,
            ),
            "1.0.0-a3-dev1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a2.dev0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=0,
            ),
            "1.0.0-a3-dev0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-b0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0b0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-b1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0b1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-rc0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-rc1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=1,
            ),
            "1.0.0-rc1-dev1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a3.dev0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.0-b0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.1",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.2",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.1.0",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.2.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.2.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.2.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.2.1",
                increment=VersionIncrement.MAJOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "2.0.0",
        ),
        # linear prerelease cases (never bump backwards on pre-releases)
        (
            VersionSchemeTestArgs(
                current_version="0.1.1b1",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.1.1-b2",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.1.1rc0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.1.1-rc1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="0.1.1rc0",
                increment=VersionIncrement.NONE,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "0.1.1-rc1",
        ),
    ],
)
def test_bump_semver_version(
    version_args: VersionSchemeTestArgs, expected_version: str
):
    assert (
        str(
            SemVer(version_args.current_version).bump(
                increment=version_args.increment,
                prerelease=version_args.prerelease,
                prerelease_offset=version_args.prerelease_offset,
                devrelease=version_args.devrelease,
            )
        )
        == expected_version
    )


@pytest.mark.parametrize(
    "version_args, expected_version",
    [
        (
            VersionSchemeTestArgs(
                current_version="1.0.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="1.0.0",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0",
        ),
        # with exact_increment=False: "1.0.0-b0"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a1",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.1-b0",
        ),
        # with exact_increment=False: "1.0.0-b1"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0b0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.1-b0",
        ),
        # with exact_increment=False: "1.0.0-rc0"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0b1",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.1-rc0",
        ),
        # with exact_increment=False: "1.0.0-rc1"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.0.1-rc0",
        ),
        # with exact_increment=False: "1.0.0-rc1-dev1"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=1,
            ),
            "1.0.1-rc0-dev1",
        ),
        # with exact_increment=False: "1.0.0-b0"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0a1",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0-b0",
        ),
        # with exact_increment=False: "1.0.0-b1"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0b0",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.BETA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0-b0",
        ),
        # with exact_increment=False: "1.0.0-rc0"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0b1",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0-rc0",
        ),
        # with exact_increment=False: "1.0.0-rc1"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=None,
            ),
            "1.1.0-rc0",
        ),
        # with exact_increment=False: "1.0.0-rc1-dev1"
        (
            VersionSchemeTestArgs(
                current_version="1.0.0rc0",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.RC,
                prerelease_offset=0,
                devrelease=1,
            ),
            "1.1.0-rc0-dev1",
        ),
        # with exact_increment=False: "2.0.0"
        (
            VersionSchemeTestArgs(
                current_version="2.0.0b0",
                increment=VersionIncrement.MAJOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "3.0.0",
        ),
        # with exact_increment=False: "2.0.0"
        (
            VersionSchemeTestArgs(
                current_version="2.0.0b0",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "2.1.0",
        ),
        # with exact_increment=False: "2.0.0"
        (
            VersionSchemeTestArgs(
                current_version="2.0.0b0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "2.0.1",
        ),
        # same with exact_increment=False
        (
            VersionSchemeTestArgs(
                current_version="2.0.0b0",
                increment=VersionIncrement.MAJOR,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "3.0.0-a0",
        ),
        # with exact_increment=False: "2.0.0b1"
        (
            VersionSchemeTestArgs(
                current_version="2.0.0b0",
                increment=VersionIncrement.MINOR,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "2.1.0-a0",
        ),
        # with exact_increment=False: "2.0.0b1"
        (
            VersionSchemeTestArgs(
                current_version="2.0.0b0",
                increment=VersionIncrement.PATCH,
                prerelease=Prerelease.ALPHA,
                prerelease_offset=0,
                devrelease=None,
            ),
            "2.0.1-a0",
        ),
    ],
)
def test_bump_semver_version_force(
    version_args: VersionSchemeTestArgs, expected_version: str
):
    assert (
        str(
            SemVer(version_args.current_version).bump(
                increment=version_args.increment,
                prerelease=version_args.prerelease,
                prerelease_offset=version_args.prerelease_offset,
                devrelease=version_args.devrelease,
                exact_increment=True,
            )
        )
        == expected_version
    )


@pytest.mark.parametrize(
    "version_args, expected_version",
    [
        (
            VersionSchemeTestArgs(
                current_version="4.5.0+0.1.0",
                increment=VersionIncrement.PATCH,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "4.5.0+0.1.1",
        ),
        (
            VersionSchemeTestArgs(
                current_version="4.5.0+0.1.1",
                increment=VersionIncrement.MINOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "4.5.0+0.2.0",
        ),
        (
            VersionSchemeTestArgs(
                current_version="4.5.0+0.2.0",
                increment=VersionIncrement.MAJOR,
                prerelease=None,
                prerelease_offset=0,
                devrelease=None,
            ),
            "4.5.0+1.0.0",
        ),
    ],
)
def test_bump_semver_version_local(
    version_args: VersionSchemeTestArgs, expected_version: str
):
    assert (
        str(
            SemVer(version_args.current_version).bump(
                increment=version_args.increment,
                prerelease=version_args.prerelease,
                prerelease_offset=version_args.prerelease_offset,
                devrelease=version_args.devrelease,
                is_local_version=True,
            )
        )
        == expected_version
    )


def test_semver_scheme_property():
    version = SemVer("0.0.1")
    assert version.scheme is SemVer


def test_semver_implement_version_protocol():
    assert isinstance(SemVer("0.0.1"), VersionProtocol)
