name: 🚀 Feature request
description: Suggest an idea for this project
title: "<One feature request per issue>"
labels: [feature]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description for us to know your idea.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: |
        A clear and concise description of what you want to happen.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
  - type: textarea
    id: related-issue
    attributes:
      label: Additional context
      description: |
        If applicable, add link to existing issue also help us know better.
