#!/usr/bin/env sh
set -e

export PREFIX='poetry run python -m '
export REGEX='^(?![.]|venv).*'

${PREFIX}pytest -n 3 --dist=loadfile --cov-report term-missing --cov-report=xml:coverage.xml --cov=commitizen tests/
${PREFIX}black commitizen tests --check
${PREFIX}ruff commitizen/ tests/
${PREFIX}mypy commitizen/ tests/
${PREFIX}commitizen -nr 3 check --rev-range origin/master..
