#!/bin/sh -e

export PREFIX="poetry run python -m "
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

${PREFIX}pytest -n 3 --cov-report term-missing --cov-report=xml:coverage.xml --cov=commitizen tests/
${PREFIX}black commitizen tests --check
${PREFIX}isort --check-only commitizen tests
${PREFIX}flake8 commitizen/ tests/
${PREFIX}mypy commitizen/ tests/
${PREFIX}pydocstyle --convention=google --add-ignore=D1,D415
