name: "Label Pull Request"
on:
- pull_request_target

jobs:
  label-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github/labeler.yml
        sparse-checkout-cone-mode: false
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yml
