name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "00 18 * * *"

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@v5

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: . --exclude-path "tests"
          fail: false

    #   - name: Create Issue From File
    #     if: steps.lychee.outputs.exit_code != 0 && github.event_name == 'schedule'
    #     uses: peter-evans/create-issue-from-file@v5
    #     with:
    #       title: Link Checker Report
    #       content-filepath: ./lychee/out.md
    #       labels: 'type: documentation'
